# name: hello-new

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   hello:
#     runs_on: ubuntu-latest
#     steps:
#       - name: jjsjsj
#         run: echo "hello yoyoyo"
#         shell: bash

name: Simple Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print message
        run: echo "Hello, GitHub Actions!"
