name: hello-new

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs_on: ubuntu-latest
    steps:
      - name: jjsjsj
        run: echo "hello yoyoyo"
        shell: bash
