name: Setup k3s Cluster

on:
  workflow_dispatch:

jobs:
  setup-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k3s
        run: |
          curl -sfL https://get.k3s.io | sh -

      - name: Check k3s status
        run: sudo systemctl status k3s

      - name: Retrieve kubeconfig
        run: sudo cat /etc/rancher/k3s/k3s.yaml
        id: kubeconfig
        continue-on-error: true

      - name: Set up kubeconfig
        run: echo "${{ steps.kubeconfig.outputs.kubeconfig }}" >> $HOME/.kube/config
