name: Comment on Issue

on:
  issues:
    types: [opened, labeled]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            -Also You can raise your issues on the project , We will take a look

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
